import Link from "next/link";

export const metadata = { title: "Risk Disclosure — FXS Trading" };

export default function RiskDisclosurePage() {
  return (
    <main className="min-h-screen px-4 py-10">
      <div className="max-w-2xl mx-auto space-y-6">
        <Link href="/signup" className="text-2xl leading-none inline-block">
          ‹
        </Link>

        <div>
          <h1 className="text-2xl font-extrabold tracking-tight mb-1">Risk Disclosure</h1>
          <p className="text-sm" style={{ color: "var(--text-muted)" }}>
            Last updated: {new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}
          </p>
        </div>

        <div
          className="rounded-xl p-4 text-sm font-semibold"
          style={{ background: "#f8717122", color: "#f87171", border: "1px solid #f87171" }}
        >
          Trading leveraged products carries a high level of risk and may not be suitable for
          everyone. You can lose some or all of your invested capital. Only trade with funds you
          can afford to lose.
        </div>

        <Section title="1. General risk of loss">
          <p>
            Trading forex and synthetic indices involves substantial risk. Prices can move rapidly and
            unpredictably, and past performance is never a reliable indicator of future results. You
            should not trade with funds you cannot afford to lose, including money needed for essential
            living expenses.
          </p>
        </Section>

        <Section title="2. Leverage risk">
          <p>
            Leverage magnifies both potential profits and potential losses. A relatively small market
            movement can result in a proportionally much larger movement in the value of your position,
            which can work against you as well as for you. You may lose more than your initial deposit
            on a leveraged position, and your account can be automatically liquidated if your margin
            becomes insufficient.
          </p>
        </Section>

        <Section title="3. Synthetic markets are simulated instruments">
          <p>
            Our synthetic indices (Volatility, Boom, Jump, and similar) are proprietary instruments
            generated by our own pricing model. They are not real-world exchange-traded assets, are not
            correlated to any real underlying market, and their price behavior — while designed to feel
            realistic — is entirely determined by our disclosed simulation parameters. Trading them
            still carries real financial risk when done with real funds, in the same way any priced,
            leveraged instrument does.
          </p>
        </Section>

        <Section title="4. Market and liquidity risk">
          <p>
            Real forex prices can be affected by economic events, political developments, and broader
            market conditions outside our control. During periods of high volatility or low liquidity,
            price gaps and slippage can occur, meaning an order may execute at a materially different
            price than expected.
          </p>
        </Section>

        <Section title="5. No investment advice">
          <p>
            Nothing on FXS Trading constitutes financial, investment, or trading advice. Any market
            commentary, charts, or tools provided are for informational purposes only. You are solely
            responsible for your own trading decisions.
          </p>
        </Section>

        <Section title="6. Technology risk">
          <p>
            Trading relies on internet connectivity and third-party infrastructure. We are not liable
            for losses resulting from connectivity issues, platform downtime, or delays outside our
            reasonable control, though we work to keep the platform reliable and available.
          </p>
        </Section>

        <Section title="7. Acknowledgment">
          <p>
            By trading on FXS Trading, you confirm that you understand these risks, that you are trading
            with funds you can afford to lose, and that you have read and accepted this Risk Disclosure
            in full.
          </p>
        </Section>
      </div>
    </main>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-2">
      <h2 className="text-base font-bold">{title}</h2>
      <div className="text-sm leading-relaxed" style={{ color: "var(--text-muted)" }}>
        {children}
      </div>
    </section>
  );
}
