import Link from "next/link";

export const metadata = { title: "FXS Trading Terms" };

export default function TradingTermsPage() {
  return (
    <main className="min-h-screen px-4 py-10">
      <div className="max-w-2xl mx-auto space-y-6">
        <Link href="/signup" className="text-2xl leading-none inline-block">
          ‹
        </Link>

        <div>
          <h1 className="text-2xl font-extrabold tracking-tight mb-1">
            <span className="fxs-logo">FXS Trading</span> Terms
          </h1>
          <p className="text-sm" style={{ color: "var(--text-muted)" }}>
            Last updated: {new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}
          </p>
        </div>

        <p className="text-sm leading-relaxed">
          These Terms govern your use of FXS Trading, including our synthetic markets, real forex
          pairs, wallet, deposits, and withdrawals. By creating an FXS Trading account, you agree to
          these Terms in addition to the general{" "}
          <Link href="/terms" className="underline" style={{ color: "var(--fxs-blue)" }}>
            Terms of Service
          </Link>{" "}
          and our{" "}
          <Link href="/risk-disclosure" className="underline" style={{ color: "var(--fxs-blue)" }}>
            Risk Disclosure
          </Link>
          .
        </p>

        <Section title="1. Eligibility and verification">
          <p>
            You must be at least 18 years old. Before your first withdrawal, and before certain deposit
            or trading limits are lifted, we require identity verification (KYC): a government-issued
            ID, a selfie, and proof of address. We reserve the right to request additional verification
            at any time, and to restrict account activity until verification is complete.
          </p>
        </Section>

        <Section title="2. Demo vs. Live accounts">
          <p>
            FXS Trading offers a Demo mode using simulated funds with no real value, and a Live mode
            using real funds. Demo balances can be claimed for practice and reset once depleted. Trades,
            balances, and history in Demo mode are entirely separate from Live mode and have no bearing
            on real funds.
          </p>
        </Section>

        <Section title="3. Synthetic markets">
          <p>
            Our synthetic indices (e.g. Volatility, Boom, Jump) are proprietary, simulated instruments
            generated by our own pricing engine. They are not real exchange-traded assets and are not
            linked to any real underlying market. Prices are generated using a disclosed statistical
            model; while designed to behave reasonably, they do not represent real-world asset prices.
          </p>
        </Section>

        <Section title="4. Real forex pairs">
          <p>
            Real forex pairs use live reference exchange rate data. Trading on these pairs with real
            funds is only available once explicitly enabled for your account, consistent with our
            regulatory status at the time. Where real-money forex trading is enabled, FXS Trading may
            act as principal counterparty to your trades, consistent with our licensed dealer status.
          </p>
        </Section>

        <Section title="5. Deposits and withdrawals">
          <ul className="list-disc pl-5 space-y-2">
            <li>Deposits are processed via our payment partners (M-Pesa, card, and bank transfer). Funds are credited once payment is confirmed.</li>
            <li>Withdrawals require completed identity verification and are reviewed before funds are released.</li>
            <li>We reserve the right to delay or decline a withdrawal where we reasonably suspect fraud, money laundering, or a violation of these Terms.</li>
            <li>Minimum deposit and withdrawal amounts may apply and are shown in-app at the time of the transaction.</li>
          </ul>
        </Section>

        <Section title="6. Margin, leverage, and liquidation">
          <p>
            Leveraged trading amplifies both gains and losses. If your account&apos;s available margin
            becomes insufficient to support your open positions, we may close positions automatically
            (including via stop-loss/take-profit triggers) without further notice. You are responsible
            for monitoring your open positions and margin levels.
          </p>
        </Section>

        <Section title="7. Account suspension and termination">
          <p>
            We may suspend or close your account for violations of these Terms, suspected fraud,
            regulatory requirements, or at our discretion with reasonable notice where practical. Any
            real funds balance will be returned to you subject to completed verification, less any
            amounts legitimately owed.
          </p>
        </Section>

        <Section title="8. Changes to these Terms">
          <p>
            We may update these Terms from time to time, particularly as our licensing and product
            offering evolves. Continued use of FXS Trading after changes take effect constitutes
            acceptance of the updated Terms.
          </p>
        </Section>

        <Section title="9. Contact">
          <p>
            Questions can be sent to{" "}
            <a href="mailto:cbhmediake@gmail.com" className="underline" style={{ color: "var(--fxs-blue)" }}>
              cbhmediake@gmail.com
            </a>.
          </p>
        </Section>
      </div>
    </main>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-2">
      <h2 className="text-base font-bold">{title}</h2>
      <div className="text-sm leading-relaxed" style={{ color: "var(--text-muted)" }}>
        {children}
      </div>
    </section>
  );
}
